#!/usr/bin/env node

var proxy = require('http-proxy-middleware');
var http = require('http');
var process = require('process');
var fs = require('fs');
var path = require('path');


var connect = require('gulp-connect');
connect.server({
    port: 80,
    root: path.resolve(__dirname, 'app', 'build'),
    middleware: function(connect, opt) {
	return [
	    proxy('/api', {
		target: 'http://127.0.0.1:8020',
		changeOrigin:true
	    })
	];
    }
});
console.log('Server running at http://0.0.0.0:80/');
console.log(`This process is pid ${process.pid}`);

pid_path = path.resolve(__dirname, 'client.pid'),
fs.writeFile(pid_path, process.pid);
